---
abstract: "Post-modern Gtk+ applications\r"
author:
  - 'Jeffrey Ray Hallock <jeffrey.hallock@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gapp
requires:
  Carp: 0
  DateTime: 0
  Gtk2: 0
  List::MoreUtils: 0.09
  Moose: 2.0
  MooseX::Clone: 0
  MooseX::LazyRequire: 0
  MooseX::SemiAffordanceAccessor: 0
  MooseX::StrictConstructor: 0
  MooseX::Types: 0
  Scalar::Util: 0
  Sub::Exporter: 0.90
version: 0.60
